"""empty message

Revision ID: a7b7528eead9
Revises: 
Create Date: 2019-09-25 21:09:10.834757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b7528eead9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_vk_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_id')
    # ### end Alembic commands ###
